### GET request to example server
GET localhost:3000/api/users
Accept: application/json


### POST create user
POST localhost:3000/api/users
Content-Type: application/json

{
  "email": "dave@dave.com",
  "name": "Dave Harms"
}


###
GET localhost:3000/api/userssss
Accept: application/json